<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enroll</name>
   <tag></tag>
   <elementGuidId>77e52b86-6d6f-4337-93e2-a6e50625d82b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tutor-btn-enroll.tutor-btn.tutor-course-purchase-btn.btn-enroll-view-course</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16f993cf-10f8-41b1-9239-d4d48c0bdf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6a036030-c39a-43c4-a9aa-3416ef0edf35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course</value>
      <webElementGuid>56d67022-4e2c-4997-9576-f0624b664456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>b68a4add-f2eb-4ad8-bb9c-f1b2186938c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-registration</value>
      <webElementGuid>6aa2982e-7be1-4fd3-a406-1958a7489c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Enroll				</value>
      <webElementGuid>e9ae2806-83ad-43c1-94d6-c9d4f8b0c8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-items-course&quot;)/div[@class=&quot;col-md-8 col-11 mb-sm-2&quot;]/div[@class=&quot;skillate-course-cart-btn d-lg-block&quot;]/div[@class=&quot;enroll-course-top enroll-course-element enroll-course-position&quot;]/div[@class=&quot;tutor-single-add-to-cart-box cart-required-login&quot;]/form[@class=&quot;tutor-enroll-form enroll-course-form&quot;]/div[@class=&quot;tutor-course-enroll-wrap&quot;]/button[@class=&quot;tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course&quot;]</value>
      <webElementGuid>dcfa5096-724a-4b4d-95e1-3c577358f05d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>5903dc8c-3bf6-4a97-a41a-7af7be292d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-items-course']/div[5]/div/div/div/form/div/button</value>
      <webElementGuid>cf5e733f-dff5-4071-bc11-32d414583cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate this course'])[1]/following::button[1]</value>
      <webElementGuid>eee79cd4-aba2-418a-b1fa-5a55cd9e9725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/following::button[1]</value>
      <webElementGuid>d800fed1-0c06-40e7-b0fd-190e253d516c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[2]</value>
      <webElementGuid>dd59df37-63b5-4a0d-b314-9008abe0b397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enroll']/parent::*</value>
      <webElementGuid>38da0cdd-b91c-4cbb-962e-0366bd21a7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>90905601-3bfb-452d-a7ba-c5c273a061d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
										Enroll				' or . = '
										Enroll				')]</value>
      <webElementGuid>7c3ce32f-3926-4cdd-9edc-d5a38bdc3c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
