<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Anywhere</name>
   <tag></tag>
   <elementGuidId>8c89b75a-c4f0-4ab7-a901-a41c124bdb80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.f16sug5q.dir.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f54218a-4ea0-4dcc-b03b-bfbe7ec8d497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f16sug5q dir dir-ltr</value>
      <webElementGuid>67c8299b-0819-48c8-9a9b-f8677608ef49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anywhere</value>
      <webElementGuid>12ec6ed1-6fe0-4db7-99f7-c9b3266dcb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scrollbar-gutter js-focus-visible dir native v1oc6b3k vgnbcm1 v1agkal2 vqw89vp vlugpmm g5l85gq&quot;]/body[@class=&quot;with-new-header&quot;]/div[5]/div[1]/div[@class=&quot;t1bgcr6e&quot;]/div[1]/div[1]/div[@class=&quot;cd56ld cb80sj1 dir dir-ltr&quot;]/div[@class=&quot;h1ta6hky dir dir-ltr&quot;]/div[@class=&quot;c1yo0219 dir dir-ltr&quot;]/div[1]/div[@class=&quot;dir dir-ltr&quot;]/header[@class=&quot;curo97c c121bpov dir dir-ltr&quot;]/div[@class=&quot;c1s03i8x c17xuogm dir dir-ltr&quot;]/div[@class=&quot;c1ujpdn9 dir dir-ltr&quot;]/div[@class=&quot;l1sjr04j l1x4ovsg llb1jct lc9d3st dir dir-ltr&quot;]/div[@class=&quot;chgx2vp dir dir-ltr&quot;]/span[@class=&quot;ieg7dag dir dir-ltr&quot;]/button[@class=&quot;ffgcxut dir dir-ltr&quot;]/div[@class=&quot;f16sug5q dir dir-ltr&quot;]</value>
      <webElementGuid>8abf92e3-435c-4572-a04d-41847aaf77d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::div[1]</value>
      <webElementGuid>b7d9a782-e3f6-45ef-9721-6a03ea7fca0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start your search'])[1]/following::div[1]</value>
      <webElementGuid>11a72ebc-9005-420f-85b0-167bb4018005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check in / Check out'])[1]/preceding::div[1]</value>
      <webElementGuid>59e2f795-2a79-4a2c-b707-c2f18e3fee48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any week'])[1]/preceding::div[1]</value>
      <webElementGuid>9af61e0d-9d78-418d-968f-f224bcba49b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anywhere']/parent::*</value>
      <webElementGuid>37e19976-0f9f-48f8-bf47-3826241c07cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>de807f8d-1754-4948-8e10-1086e2d28ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Anywhere' or . = 'Anywhere')]</value>
      <webElementGuid>c72195fa-e5ad-4434-8cfd-47f36f17b581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
