<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add guests_svys41v dir dir-ltr</name>
   <tag></tag>
   <elementGuidId>2edca0f9-0215-4a72-b500-8e01e285c579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.svys41v.dir.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Add guests'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47f7523f-0895-4d93-b309-76cf6071b38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svys41v dir dir-ltr</value>
      <webElementGuid>f8e90193-48c9-40f7-a922-b624980c420e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>little-search-icon</value>
      <webElementGuid>87fc5a40-5e0d-445a-93da-0b8a9df81e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f20f21b3-0ff2-4c3d-9db2-19a6f6291378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scrollbar-gutter js-focus-visible dir native v1oc6b3k vgnbcm1 v1agkal2 vqw89vp vlugpmm g5l85gq&quot;]/body[@class=&quot;with-new-header&quot;]/div[5]/div[1]/div[@class=&quot;t1bgcr6e&quot;]/div[1]/div[1]/div[@class=&quot;cd56ld cb80sj1 dir dir-ltr&quot;]/div[@class=&quot;h1ta6hky dir dir-ltr&quot;]/div[@class=&quot;c1yo0219 dir dir-ltr&quot;]/div[1]/div[@class=&quot;dir dir-ltr&quot;]/header[@class=&quot;curo97c c121bpov dir dir-ltr&quot;]/div[@class=&quot;c1s03i8x c17xuogm dir dir-ltr&quot;]/div[@class=&quot;c1ujpdn9 dir dir-ltr&quot;]/div[@class=&quot;l1sjr04j l1x4ovsg llb1jct lc9d3st dir dir-ltr&quot;]/div[@class=&quot;chgx2vp dir dir-ltr&quot;]/span[@class=&quot;ieg7dag dir dir-ltr&quot;]/button[@class=&quot;ffgcxut dir dir-ltr&quot;]/div[@class=&quot;svys41v dir dir-ltr&quot;]</value>
      <webElementGuid>3d122e9d-2517-4767-bdec-263c7618420f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add guests'])[1]/following::div[1]</value>
      <webElementGuid>09ce9a17-22ac-4be3-82d7-62379fa0c5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guests'])[1]/following::div[2]</value>
      <webElementGuid>d7e33d72-1517-4742-b0c6-bc7c2ff74d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stays'])[1]/preceding::div[2]</value>
      <webElementGuid>1c693af2-cbf3-4d53-a31b-7b8c58da9127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experiences'])[1]/preceding::div[4]</value>
      <webElementGuid>20923c33-f2c7-4f4b-a4d0-abfbcde56dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/div[2]</value>
      <webElementGuid>7f28f5ad-66b5-43ad-a33e-f6907fba8ab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
