<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add guests_t1dqvypu dir dir-ltr</name>
   <tag></tag>
   <elementGuidId>4938a622-f1e5-4fe6-a59b-64305e92887a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.t1dqvypu.dir.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-tabpanel']/div/div[5]/div/div[3]/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49e26c15-e0db-4164-ab26-4bad1adf5e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t1dqvypu dir dir-ltr</value>
      <webElementGuid>ec9ca379-4ca9-4a0d-af9e-b26e27efb1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-tabpanel&quot;)/div[@class=&quot;ir2ixub dir dir-ltr&quot;]/div[@class=&quot;c111bvlt c1gh7ier dir dir-ltr&quot;]/div[@class=&quot;c1ddhymz cggll98 dir dir-ltr&quot;]/div[@class=&quot;s1t4vwjw dir dir-ltr&quot;]/button[@class=&quot;bhtghtc b1tqc7mb dir dir-ltr&quot;]/span[@class=&quot;t1ng71ne dir dir-ltr&quot;]/span[@class=&quot;t1dqvypu dir dir-ltr&quot;]</value>
      <webElementGuid>09980509-62bc-4db5-8c0d-290d9905a2f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div[5]/div/div[3]/button/span/span</value>
      <webElementGuid>001aef6b-37cc-4145-bf5d-7a3a725f17c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/span</value>
      <webElementGuid>aa5b1acd-3a82-4fd0-9b5c-a59c6c752ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div[5]/div/div[2]/button/span/span</value>
      <webElementGuid>52aae3de-5d61-4c5b-bd4b-e351c6280c97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
